/** The offline word pool: `/words.json` is generated by backend/scripts/export_words.py from
 * the enabled categories/words and precached by the PWA like any other static asset — see
 * the plan's "word bank as a static bundle" decision. Fetched once per session and cached. */

export interface BankWord {
  id: number
  word: string
  similar_word: string | null
}

export interface BankCategory {
  id: number
  name: string
  words: BankWord[]
}

export interface CategorySummary {
  id: number
  name: string
  word_count: number
}

let bankPromise: Promise<BankCategory[]> | null = null

export function loadWordBank(): Promise<BankCategory[]> {
  if (!bankPromise) {
    bankPromise = fetch('/words.json').then((res) => res.json() as Promise<BankCategory[]>)
  }
  return bankPromise
}

export async function listCategorySummaries(): Promise<CategorySummary[]> {
  const bank = await loadWordBank()
  return bank
    .map((c) => ({ id: c.id, name: c.name, word_count: c.words.length }))
    .sort((a, b) => a.name.localeCompare(b.name))
}
