# Similar Word mode: category -> {word: related word given to the Impostors}.
# A good pair is close enough that the Impostor's clues sound plausible, but different
# enough that careful listeners can spot them (Penguin -> Puffin, Pizza -> Burger).
SIMILAR_WORDS: dict[str, dict[str, str]] = {
    "Animals": {
        "Dog": "Cat",
        "Cat": "Dog",
        "Elephant": "Rhino",
        "Giraffe": "Zebra",
        "Penguin": "Puffin",
        "Lion": "Tiger",
        "Monkey": "Gorilla",
        "Horse": "Donkey",
        "Rabbit": "Hamster",
        "Shark": "Whale",
        "Tiger": "Leopard",
        "Dolphin": "Shark",
        "Octopus": "Squid",
        "Kangaroo": "Koala",
        "Owl": "Eagle",
        "Crocodile": "Alligator",
        "Bat": "Owl",
        "Camel": "Llama",
        "Flamingo": "Swan",
        "Koala": "Panda",
        "Peacock": "Parrot",
        "Squirrel": "Chipmunk",
        "Turtle": "Tortoise",
        "Platypus": "Beaver",
        "Chameleon": "Iguana",
        "Sloth": "Koala",
        "Jellyfish": "Octopus",
        "Armadillo": "Hedgehog",
        "Narwhal": "Walrus",
        "Hedgehog": "Porcupine",
        "Seahorse": "Starfish",
        "Porcupine": "Hedgehog",
        "Carabao": "Cow",
        "Tarsier": "Lemur",
    },
    "Food": {
        "Pizza": "Burger",
        "Burger": "Sandwich",
        "Ice Cream": "Frozen Yogurt",
        "Pancakes": "Waffles",
        "Spaghetti": "Ramen",
        "Fried Chicken": "Chicken Nuggets",
        "Hotdog": "Sausage",
        "French Fries": "Potato Chips",
        "Sandwich": "Burger",
        "Chocolate": "Candy",
        "Donut": "Bagel",
        "Sushi": "Sashimi",
        "Tacos": "Burrito",
        "Adobo": "Afritada",
        "Ramen": "Pho",
        "Popcorn": "Potato Chips",
        "Lasagna": "Spaghetti",
        "Dumplings": "Siomai",
        "Sinigang": "Tinola",
        "Lumpia": "Siomai",
        "Burrito": "Tacos",
        "Curry": "Stew",
        "Waffles": "Pancakes",
        "Cheesecake": "Cupcake",
        "Halo-Halo": "Mais Con Yelo",
        "Lechon": "Barbecue",
        "Fondue": "Hot Pot",
        "Paella": "Fried Rice",
        "Croissant": "Bread",
        "Kimchi": "Pickles",
        "Balut": "Boiled Egg",
        "Kare-Kare": "Adobo",
        "Tiramisu": "Cake",
        "Pho": "Ramen",
        "Bibimbap": "Fried Rice",
        "Sisig": "Chicharon",
    },
    "Places": {
        "Beach": "Pool",
        "School": "University",
        "Hospital": "Clinic",
        "Airport": "Train Station",
        "Zoo": "Aquarium",
        "Supermarket": "Mall",
        "Park": "Garden",
        "Mall": "Market",
        "Restaurant": "Cafe",
        "Playground": "Park",
        "Library": "Bookstore",
        "Museum": "Art Gallery",
        "Cinema": "Theater",
        "Gym": "Spa",
        "Church": "Temple",
        "Bakery": "Cafe",
        "Farm": "Ranch",
        "Hotel": "Resort",
        "Stadium": "Arena",
        "Train Station": "Bus Station",
        "Water Park": "Amusement Park",
        "Barber Shop": "Salon",
        "Karaoke Bar": "Night Club",
        "Lighthouse": "Tower",
        "Casino": "Arcade",
        "Submarine": "Ship",
        "Space Station": "Rocket",
        "Volcano": "Mountain",
        "Prison": "Police Station",
        "Castle": "Palace",
        "Igloo": "Tent",
        "Haunted House": "Graveyard",
        "Cruise Ship": "Ferry",
        "Desert Island": "Beach",
        "Observatory": "Planetarium",
    },
    "Objects": {
        "Chair": "Stool",
        "Umbrella": "Raincoat",
        "Toothbrush": "Comb",
        "Pillow": "Blanket",
        "Clock": "Watch",
        "Mirror": "Window",
        "Spoon": "Fork",
        "Key": "Lock",
        "Book": "Magazine",
        "Cup": "Bowl",
        "Backpack": "Suitcase",
        "Candle": "Lamp",
        "Scissors": "Knife",
        "Wallet": "Purse",
        "Ladder": "Stairs",
        "Guitar": "Ukulele",
        "Flashlight": "Lantern",
        "Paintbrush": "Pencil",
        "Basket": "Bucket",
        "Hammer": "Screwdriver",
        "Remote Control": "Phone",
        "Compass": "Map",
        "Hourglass": "Stopwatch",
        "Stapler": "Tape",
        "Magnifying Glass": "Binoculars",
        "Thermometer": "Scale",
        "Telescope": "Binoculars",
        "Anchor": "Rope",
        "Doorbell": "Alarm",
        "Calculator": "Abacus",
        "Paper Clip": "Safety Pin",
    },
    "Movies": {
        "Titanic": "Avatar",
        "Frozen": "Tangled",
        "Toy Story": "Monsters, Inc.",
        "Shrek": "Puss in Boots",
        "Jurassic Park": "King Kong",
        "Finding Nemo": "Shark Tale",
        "Cars": "Planes",
        "Moana": "Frozen",
        "Minions": "Despicable Me",
        "Coco": "Encanto",
        "The Lion King": "The Jungle Book",
        "Avatar": "Titanic",
        "Harry Potter": "The Lord of the Rings",
        "Star Wars": "Star Trek",
        "Spider-Man": "Batman",
        "Avengers": "Justice League",
        "Batman": "Superman",
        "Encanto": "Coco",
        "Kung Fu Panda": "Madagascar",
        "Ghostbusters": "Men in Black",
        "Home Alone": "Mrs. Doubtfire",
        "Inception": "Interstellar",
        "Parasite": "Joker",
        "The Matrix": "Terminator",
        "Jaws": "The Meg",
        "Up": "WALL-E",
        "Interstellar": "Gravity",
        "Gravity": "Interstellar",
        "Ratatouille": "Stuart Little",
        "Top Gun": "Fast & Furious",
        "Godzilla": "King Kong",
        "The Godfather": "Scarface",
        "Back to the Future": "Jumanji",
    },
    "Technology": {
        "Smartphone": "Tablet",
        "Laptop": "Desktop Computer",
        "Television": "Projector",
        "Headphones": "Earbuds",
        "Camera": "Webcam",
        "Keyboard": "Mouse",
        "Tablet": "E-Reader",
        "Video Game": "Board Game",
        "Charger": "Battery",
        "Drone": "Remote Control Car",
        "Smartwatch": "Fitness Tracker",
        "Robot": "Cyborg",
        "Printer": "Scanner",
        "Microwave": "Oven",
        "Wi-Fi": "Bluetooth",
        "Selfie Stick": "Tripod",
        "Speaker": "Microphone",
        "Game Console": "Arcade Machine",
        "Power Bank": "Charger",
        "Electric Scooter": "Hoverboard",
        "Bluetooth": "Wi-Fi",
        "Satellite": "Space Station",
        "Virtual Reality": "Augmented Reality",
        "Cloud Storage": "USB Drive",
        "QR Code": "Barcode",
        "Artificial Intelligence": "Robot",
        "3D Printer": "Printer",
        "Password": "PIN Code",
        "Solar Panel": "Wind Turbine",
        "Self-Driving Car": "Electric Car",
        "Emoji": "Sticker",
    },
    "Jobs": {
        "Doctor": "Nurse",
        "Teacher": "Principal",
        "Firefighter": "Paramedic",
        "Chef": "Baker",
        "Police Officer": "Security Guard",
        "Farmer": "Gardener",
        "Singer": "Dancer",
        "Baker": "Chef",
        "Driver": "Pilot",
        "Artist": "Designer",
        "Pilot": "Flight Attendant",
        "Dentist": "Doctor",
        "Lifeguard": "Coast Guard",
        "Mechanic": "Engineer",
        "Photographer": "Videographer",
        "Nurse": "Doctor",
        "Waiter": "Bartender",
        "Scientist": "Inventor",
        "Soldier": "Police Officer",
        "Barber": "Hairdresser",
        "Veterinarian": "Zookeeper",
        "Tour Guide": "Travel Agent",
        "Astronaut": "Pilot",
        "Architect": "Engineer",
        "Magician": "Clown",
        "Librarian": "Teacher",
        "Detective": "Spy",
        "Plumber": "Electrician",
        "Judge": "Lawyer",
        "Zookeeper": "Veterinarian",
        "Stuntman": "Actor",
        "Lawyer": "Judge",
        "Electrician": "Plumber",
        "DJ": "Singer",
    },
    "Sports": {
        "Basketball": "Volleyball",
        "Football": "Rugby",
        "Swimming": "Diving",
        "Tennis": "Badminton",
        "Boxing": "Wrestling",
        "Running": "Cycling",
        "Volleyball": "Basketball",
        "Baseball": "Cricket",
        "Badminton": "Tennis",
        "Golf": "Billiards",
        "Skateboarding": "Surfing",
        "Bowling": "Billiards",
        "Surfing": "Skateboarding",
        "Cycling": "Running",
        "Table Tennis": "Badminton",
        "Wrestling": "Boxing",
        "Fencing": "Kendo",
        "Archery": "Darts",
        "Curling": "Bowling",
        "Gymnastics": "Cheerleading",
        "Sumo": "Wrestling",
        "Polo": "Horse Racing",
        "Rock Climbing": "Hiking",
        "Billiards": "Bowling",
    },
    "Music": {
        "Piano": "Organ",
        "Drums": "Tambourine",
        "Violin": "Cello",
        "Karaoke": "Concert",
        "Concert": "Festival",
        "Microphone": "Speaker",
        "Trumpet": "Trombone",
        "Lullaby": "Love Song",
        "Saxophone": "Trumpet",
        "Ukulele": "Guitar",
        "Harmonica": "Flute",
        "Rap": "Rock",
        "Choir": "Orchestra",
        "Orchestra": "Band",
        "Flute": "Recorder",
        "Jazz": "Blues",
        "Accordion": "Harmonica",
        "Harp": "Piano",
        "Xylophone": "Drums",
        "Opera": "Musical",
        "Bagpipes": "Accordion",
        "Metronome": "Clock",
        "Tambourine": "Maracas",
        "Cello": "Violin",
    },
    "Countries": {
        "Philippines": "Indonesia",
        "Japan": "Korea",
        "USA": "Canada",
        "China": "Japan",
        "France": "Italy",
        "Italy": "Spain",
        "Brazil": "Argentina",
        "Australia": "New Zealand",
        "Mexico": "Spain",
        "Egypt": "Morocco",
        "India": "Nepal",
        "Canada": "USA",
        "Korea": "Japan",
        "Spain": "Portugal",
        "Thailand": "Vietnam",
        "Germany": "Austria",
        "Iceland": "Greenland",
        "Peru": "Chile",
        "Greece": "Turkey",
        "Kenya": "Tanzania",
        "Switzerland": "Austria",
        "Norway": "Sweden",
        "Vietnam": "Thailand",
        "Turkey": "Greece",
    },
    "Clothing": {
        "Shirt": "Blouse",
        "Hat": "Cap",
        "Socks": "Stockings",
        "Jeans": "Shorts",
        "Dress": "Skirt",
        "Jacket": "Coat",
        "Shoes": "Boots",
        "Pajamas": "Robe",
        "Scarf": "Shawl",
        "Gloves": "Mittens",
        "Hoodie": "Sweater",
        "Sunglasses": "Eyeglasses",
        "Raincoat": "Poncho",
        "Sandals": "Slippers",
        "Necktie": "Bow Tie",
        "Uniform": "Costume",
        "Tuxedo": "Suit",
        "Kimono": "Hanbok",
        "Barong": "Polo Shirt",
        "Overalls": "Jumpsuit",
        "Apron": "Bib",
        "Bow Tie": "Necktie",
        "Swimsuit": "Wetsuit",
        "Crown": "Tiara",
    },
    "Vehicles": {
        "Car": "Van",
        "Bus": "Train",
        "Bicycle": "Motorcycle",
        "Airplane": "Helicopter",
        "Train": "Subway",
        "Boat": "Ship",
        "Motorcycle": "Scooter",
        "Taxi": "Limousine",
        "Jeepney": "Bus",
        "Helicopter": "Airplane",
        "Ambulance": "Fire Truck",
        "Fire Truck": "Police Car",
        "Tricycle": "Pedicab",
        "Skateboard": "Scooter",
        "Truck": "Van",
        "Yacht": "Sailboat",
        "Hot Air Balloon": "Blimp",
        "Rocket": "Space Shuttle",
        "Tank": "Armored Truck",
        "Cable Car": "Ski Lift",
        "Gondola": "Rowboat",
        "Bulldozer": "Excavator",
        "Canoe": "Kayak",
        "Zeppelin": "Hot Air Balloon",
    },
    "Hobbies": {
        "Reading": "Writing",
        "Dancing": "Singing",
        "Cooking": "Baking",
        "Drawing": "Painting",
        "Singing": "Dancing",
        "Fishing": "Boating",
        "Gaming": "Board Games",
        "Shopping": "Thrifting",
        "Camping": "Hiking",
        "Gardening": "Farming",
        "Knitting": "Sewing",
        "Photography": "Filming",
        "Hiking": "Camping",
        "Baking": "Cooking",
        "Yoga": "Meditation",
        "Puzzles": "Crosswords",
        "Origami": "Scrapbooking",
        "Scuba Diving": "Snorkeling",
        "Pottery": "Sculpting",
        "Magic Tricks": "Juggling",
        "Birdwatching": "Stargazing",
        "Juggling": "Magic Tricks",
        "Calligraphy": "Painting",
        "Chess": "Checkers",
    },
    "Nature": {
        "Sun": "Star",
        "Moon": "Star",
        "Rain": "Snow",
        "Tree": "Bush",
        "Flower": "Plant",
        "Rainbow": "Sunset",
        "Mountain": "Hill",
        "Ocean": "Lake",
        "Waterfall": "River",
        "Thunder": "Lightning",
        "Forest": "Jungle",
        "Cave": "Tunnel",
        "River": "Lake",
        "Snow": "Hail",
        "Cloud": "Fog",
        "Island": "Beach",
        "Earthquake": "Tsunami",
        "Tornado": "Hurricane",
        "Glacier": "Iceberg",
        "Coral Reef": "Lagoon",
        "Eclipse": "Full Moon",
        "Quicksand": "Mud",
        "Typhoon": "Tornado",
        "Aurora": "Rainbow",
    },
    "Celebrations": {
        "Birthday": "Anniversary",
        "Christmas": "New Year",
        "Wedding": "Engagement",
        "Halloween": "Costume Party",
        "New Year": "Christmas",
        "Party": "Picnic",
        "Valentine's Day": "Anniversary",
        "Graduation": "Prom",
        "Easter": "Christmas",
        "Fiesta": "Festival",
        "Baby Shower": "Bridal Shower",
        "Picnic": "Barbecue",
        "Anniversary": "Birthday",
        "Fireworks": "Sparklers",
        "Parade": "Carnival",
        "Reunion": "Party",
        "Debut": "Prom",
        "Thanksgiving": "Christmas",
        "Chinese New Year": "New Year",
        "Carnival": "Parade",
        "Funeral": "Wake",
        "Prom": "Debut",
        "Baptism": "Wedding",
        "Sleepover": "Camping",
    },
    "Fantasy": {
        "Dragon": "Dinosaur",
        "Unicorn": "Pegasus",
        "Ghost": "Zombie",
        "Mermaid": "Siren",
        "Wizard": "Witch",
        "Fairy": "Angel",
        "Vampire": "Werewolf",
        "Zombie": "Mummy",
        "Werewolf": "Vampire",
        "Witch": "Wizard",
        "Giant": "Troll",
        "Pirate": "Viking",
        "Alien": "Robot",
        "Genie": "Fairy Godmother",
        "Elf": "Dwarf",
        "Superhero": "Villain",
        "Phoenix": "Dragon",
        "Minotaur": "Centaur",
        "Kraken": "Sea Serpent",
        "Aswang": "Manananggal",
        "Tikbalang": "Kapre",
        "Centaur": "Minotaur",
        "Griffin": "Phoenix",
        "Yeti": "Bigfoot",
    },
    "Household": {
        "Bed": "Crib",
        "Sofa": "Armchair",
        "Fridge": "Freezer",
        "Door": "Gate",
        "Window": "Door",
        "Table": "Desk",
        "Lamp": "Candle",
        "Toilet": "Sink",
        "Bathtub": "Shower",
        "Washing Machine": "Dryer",
        "Electric Fan": "Aircon",
        "Rice Cooker": "Slow Cooker",
        "Curtains": "Blinds",
        "Doormat": "Rug",
        "Bookshelf": "Cabinet",
        "Blender": "Mixer",
        "Chandelier": "Lamp",
        "Fireplace": "Heater",
        "Attic": "Basement",
        "Dishwasher": "Sink",
        "Hammock": "Bed",
        "Garage": "Shed",
        "Vacuum Cleaner": "Broom",
        "Ceiling Fan": "Electric Fan",
    },
    "Games & Toys": {
        "Ball": "Balloon",
        "Doll": "Action Figure",
        "Kite": "Paper Plane",
        "Yo-Yo": "Spinning Top",
        "Teddy Bear": "Doll",
        "Lego": "Puzzle",
        "Balloon": "Ball",
        "Playing Cards": "Dominoes",
        "Monopoly": "Scrabble",
        "Hide and Seek": "Tag",
        "Jenga": "Dominoes",
        "Rubik's Cube": "Puzzle",
        "Slide": "Swing",
        "Tag": "Hide and Seek",
        "Marbles": "Jacks",
        "Water Gun": "Water Balloon",
        "Piñata": "Balloon",
        "Dominoes": "Jenga",
        "Hopscotch": "Jump Rope",
        "Jigsaw Puzzle": "Rubik's Cube",
        "Spinning Top": "Yo-Yo",
        "Trampoline": "Bouncy Castle",
        "Bingo": "Lottery",
        "Sudoku": "Crossword",
    },
    "Body": {
        "Nose": "Ear",
        "Hand": "Foot",
        "Eye": "Ear",
        "Ear": "Nose",
        "Hair": "Beard",
        "Mouth": "Lips",
        "Foot": "Hand",
        "Teeth": "Tongue",
        "Elbow": "Knee",
        "Knee": "Elbow",
        "Tongue": "Teeth",
        "Shoulder": "Hip",
        "Eyebrow": "Eyelash",
        "Belly Button": "Mole",
        "Thumb": "Big Toe",
        "Heart": "Lungs",
        "Skeleton": "Skull",
        "Brain": "Heart",
        "Ankle": "Wrist",
        "Lungs": "Heart",
        "Wrist": "Ankle",
        "Dimple": "Freckles",
        "Fingerprint": "Footprint",
        "Freckles": "Moles",
    },
    "Brands": {
        "Nike": "Adidas",
        "Apple": "Samsung",
        "McDonald's": "Jollibee",
        "Coca-Cola": "Pepsi",
        "Samsung": "Apple",
        "Google": "Bing",
        "Disney": "Pixar",
        "Jollibee": "McDonald's",
        "KFC": "Popeyes",
        "Adidas": "Puma",
        "Starbucks": "Dunkin'",
        "Netflix": "Disney+",
        "IKEA": "Walmart",
        "Toyota": "Honda",
        "Amazon": "eBay",
        "YouTube": "TikTok",
        "7-Eleven": "Ministop",
        "Shopee": "Lazada",
        "Rolex": "Omega",
        "Tesla": "BMW",
        "Gucci": "Prada",
        "Ferrari": "Lamborghini",
        "Nintendo": "PlayStation",
        "Spotify": "Apple Music",
        "Louis Vuitton": "Chanel",
        "Red Bull": "Monster",
        "Lamborghini": "Ferrari",
    },
    "Celebrities": {
        "Taylor Swift": "Katy Perry",
        "Beyoncé": "Rihanna",
        "Cristiano Ronaldo": "Lionel Messi",
        "Lionel Messi": "Cristiano Ronaldo",
        "Michael Jackson": "Elvis Presley",
        "Elvis Presley": "Michael Jackson",
        "Lady Gaga": "Madonna",
        "Rihanna": "Beyoncé",
        "Leonardo DiCaprio": "Brad Pitt",
        "Justin Bieber": "Shawn Mendes",
        "Ariana Grande": "Selena Gomez",
        "Ed Sheeran": "Shawn Mendes",
        "Billie Eilish": "Olivia Rodrigo",
        "Dwayne Johnson": "John Cena",
        "Tom Cruise": "Tom Hanks",
        "Oprah Winfrey": "Ellen DeGeneres",
        "Keanu Reeves": "Tom Cruise",
        "Bruno Mars": "The Weeknd",
        "Elon Musk": "Mark Zuckerberg",
        "MrBeast": "PewDiePie",
        "BTS": "BLACKPINK",
        "Zendaya": "Tom Holland",
        "Bad Bunny": "J Balvin",
        "Kim Kardashian": "Kylie Jenner",
        "Gordon Ramsay": "Jamie Oliver",
        "Jackie Chan": "Bruce Lee",
        "Shakira": "Jennifer Lopez",
        "Selena Gomez": "Ariana Grande",
        "LeBron James": "Michael Jordan",
    },
    "Pinoy Celebrities": {
        "Manny Pacquiao": "Nonito Donaire",
        "Vice Ganda": "Vhong Navarro",
        "Sarah Geronimo": "Regine Velasquez",
        "Kathryn Bernardo": "Liza Soberano",
        "Daniel Padilla": "Enrique Gil",
        "Coco Martin": "Piolo Pascual",
        "Anne Curtis": "Angel Locsin",
        "Marian Rivera": "Heart Evangelista",
        "Dingdong Dantes": "Alden Richards",
        "Vic Sotto": "Joey de Leon",
        "Pia Wurtzbach": "Catriona Gray",
        "Catriona Gray": "Pia Wurtzbach",
        "Regine Velasquez": "Sarah Geronimo",
        "Lea Salonga": "Regine Velasquez",
        "Alden Richards": "Dingdong Dantes",
        "Maine Mendoza": "Kathryn Bernardo",
        "Nadine Lustre": "Liza Soberano",
        "James Reid": "Daniel Padilla",
        "Liza Soberano": "Kathryn Bernardo",
        "Enrique Gil": "Daniel Padilla",
        "SB19": "BINI",
        "BINI": "SB19",
        "Dolphy": "Vic Sotto",
        "Nora Aunor": "Vilma Santos",
        "Sharon Cuneta": "Nora Aunor",
        "Ivana Alawi": "Alex Gonzaga",
        "Mimiyuuuh": "Ivana Alawi",
        "Toni Gonzaga": "Alex Gonzaga",
        "Jessica Soho": "Korina Sanchez",
        "Hidilyn Diaz": "Carlos Yulo",
        "Carlos Yulo": "Hidilyn Diaz",
        "Arnel Pineda": "Gary Valenciano",
    },
    "Fictional Characters": {
        "Mickey Mouse": "Donald Duck",
        "SpongeBob": "Patrick Star",
        "Pikachu": "Jigglypuff",
        "Mario": "Luigi",
        "Superman": "Batman",
        "Elsa": "Rapunzel",
        "Darth Vader": "Voldemort",
        "Barbie": "Ken",
        "Cinderella": "Snow White",
        "Sherlock Holmes": "Detective Conan",
        "Hermione Granger": "Harry Potter",
        "Iron Man": "Captain America",
        "Buzz Lightyear": "Woody",
        "Winnie the Pooh": "Paddington",
        "Homer Simpson": "Peter Griffin",
        "Sonic": "Pac-Man",
        "Hello Kitty": "My Melody",
        "Doraemon": "Totoro",
        "Naruto": "Goku",
        "Goku": "Naruto",
        "Dora the Explorer": "Diego",
        "Darna": "Wonder Woman",
        "Captain Barbell": "Superman",
        "Gollum": "Dobby",
        "Sailor Moon": "Cardcaptor Sakura",
        "Scooby-Doo": "Snoopy",
        "Garfield": "Tom Cat",
        "Wednesday Addams": "Coraline",
        "Jack Sparrow": "Captain Hook",
        "Dracula": "Frankenstein",
        "Pinocchio": "Peter Pan",
        "Luffy": "Naruto",
    },
}
