# "Word hint" mode: category -> {word: a single associated word given to Impostors}.
# Keep it loose, not a definition - one evocative word that nudges without describing the
# word outright (Penguin -> "Antarctica", not "A flightless bird that waddles on ice").
WORD_HINTS: dict[str, dict[str, str]] = {
    "Animals": {
        "Dog": "Loyal",
        "Cat": "Independent",
        "Elephant": "Circus",
        "Giraffe": "Towering",
        "Penguin": "Antarctica",
        "Lion": "Pride",
        "Monkey": "Mischief",
        "Horse": "Gallop",
        "Rabbit": "Hop",
        "Shark": "Ocean",
        "Tiger": "Fierce",
        "Dolphin": "Playful",
        "Octopus": "Ink",
        "Kangaroo": "Bounce",
        "Owl": "Wise",
        "Crocodile": "Snap",
        "Bat": "Night",
        "Camel": "Hump",
        "Flamingo": "Flock",
        "Koala": "Sleepy",
        "Peacock": "Vain",
        "Squirrel": "Bushy",
        "Turtle": "Patient",
        "Platypus": "Strange",
        "Chameleon": "Blend",
        "Sloth": "Lazy",
        "Jellyfish": "Drift",
        "Armadillo": "Curl",
        "Narwhal": "Unicorn",
        "Hedgehog": "Prickly",
        "Seahorse": "Tiny",
        "Porcupine": "Sharp",
        "Carabao": "Plow",
        "Tarsier": "Nocturnal",
    },
    "Food": {
        "Pizza": "Italy",
        "Burger": "Grill",
        "Ice Cream": "Melt",
        "Pancakes": "Syrup",
        "Spaghetti": "Twirl",
        "Fried Chicken": "Crispy",
        "Hotdog": "Ballpark",
        "French Fries": "Ketchup",
        "Sandwich": "Lunch",
        "Chocolate": "Sweet",
        "Donut": "Glaze",
        "Sushi": "Japan",
        "Tacos": "Tuesday",
        "Adobo": "Simmer",
        "Ramen": "Slurp",
        "Popcorn": "Movies",
        "Lasagna": "Layers",
        "Dumplings": "Steam",
        "Sinigang": "Sour",
        "Lumpia": "Fiesta",
        "Burrito": "Wrap",
        "Curry": "Spicy",
        "Waffles": "Brunch",
        "Cheesecake": "Creamy",
        "Halo-Halo": "Summer",
        "Lechon": "Fiesta",
        "Fondue": "Dip",
        "Paella": "Spain",
        "Croissant": "Bakery",
        "Kimchi": "Korea",
        "Balut": "Dare",
        "Kare-Kare": "Peanut",
        "Tiramisu": "Coffee",
        "Pho": "Vietnam",
        "Bibimbap": "Bowl",
        "Sisig": "Sizzle",
    },
    "Places": {
        "Beach": "Sandy",
        "School": "Lessons",
        "Hospital": "Emergency",
        "Airport": "Departure",
        "Zoo": "Cages",
        "Supermarket": "Groceries",
        "Park": "Bench",
        "Mall": "Shops",
        "Restaurant": "Menu",
        "Playground": "Recess",
        "Library": "Quiet",
        "Museum": "Exhibit",
        "Cinema": "Popcorn",
        "Gym": "Workout",
        "Church": "Prayer",
        "Bakery": "Fresh",
        "Farm": "Harvest",
        "Hotel": "Lobby",
        "Stadium": "Crowd",
        "Train Station": "Platform",
        "Water Park": "Splash",
        "Barber Shop": "Trim",
        "Karaoke Bar": "Sing",
        "Lighthouse": "Coast",
        "Casino": "Jackpot",
        "Submarine": "Depths",
        "Space Station": "Orbit",
        "Volcano": "Eruption",
        "Prison": "Guarded",
        "Castle": "Kingdom",
        "Igloo": "Arctic",
        "Haunted House": "Spooky",
        "Cruise Ship": "Voyage",
        "Desert Island": "Stranded",
        "Observatory": "Stargazing",
    },
    "Objects": {
        "Chair": "Sit",
        "Umbrella": "Rain",
        "Toothbrush": "Bristles",
        "Pillow": "Soft",
        "Clock": "Ticking",
        "Mirror": "Reflection",
        "Spoon": "Scoop",
        "Key": "Unlock",
        "Book": "Pages",
        "Cup": "Sip",
        "Backpack": "Straps",
        "Candle": "Flicker",
        "Scissors": "Snip",
        "Wallet": "Pocket",
        "Ladder": "Climb",
        "Guitar": "Strum",
        "Flashlight": "Beam",
        "Paintbrush": "Canvas",
        "Basket": "Woven",
        "Hammer": "Pound",
        "Remote Control": "Channels",
        "Compass": "Direction",
        "Hourglass": "Trickle",
        "Stapler": "Clip",
        "Magnifying Glass": "Zoom",
        "Thermometer": "Fever",
        "Telescope": "Stars",
        "Anchor": "Harbor",
        "Doorbell": "Chime",
        "Calculator": "Numbers",
        "Paper Clip": "Bent",
    },
    "Movies": {
        "Titanic": "Iceberg",
        "Frozen": "Sisters",
        "Toy Story": "Playtime",
        "Shrek": "Swamp",
        "Jurassic Park": "Dinosaurs",
        "Finding Nemo": "Reef",
        "Cars": "Racetrack",
        "Moana": "Voyage",
        "Minions": "Goggles",
        "Coco": "Afterlife",
        "The Lion King": "Pridelands",
        "Avatar": "Pandora",
        "Harry Potter": "Wizardry",
        "Star Wars": "Galaxy",
        "Spider-Man": "Webslinger",
        "Avengers": "Teamup",
        "Batman": "Gotham",
        "Encanto": "Magic",
        "Kung Fu Panda": "Dojo",
        "Ghostbusters": "Paranormal",
        "Home Alone": "Burglars",
        "Inception": "Dreamscape",
        "Parasite": "Class",
        "The Matrix": "Simulation",
        "Jaws": "Beachgoers",
        "Up": "Balloons",
        "Interstellar": "Wormhole",
        "Gravity": "Weightless",
        "Ratatouille": "Kitchen",
        "Top Gun": "Cockpit",
        "Godzilla": "Rampage",
        "The Godfather": "Mafia",
        "Back to the Future": "DeLorean",
    },
    "Technology": {
        "Smartphone": "Apps",
        "Laptop": "Portable",
        "Television": "Broadcast",
        "Headphones": "Playlist",
        "Camera": "Snapshot",
        "Keyboard": "Typing",
        "Tablet": "Touchscreen",
        "Video Game": "Controller",
        "Charger": "Battery",
        "Drone": "Aerial",
        "Smartwatch": "Fitness",
        "Robot": "Automation",
        "Printer": "Ink",
        "Microwave": "Reheat",
        "Wi-Fi": "Signal",
        "Selfie Stick": "Angle",
        "Speaker": "Volume",
        "Game Console": "Multiplayer",
        "Power Bank": "Recharge",
        "Electric Scooter": "Commute",
        "Bluetooth": "Pairing",
        "Satellite": "Orbit",
        "Virtual Reality": "Headset",
        "Cloud Storage": "Backup",
        "QR Code": "Scan",
        "Artificial Intelligence": "Algorithm",
        "3D Printer": "Layering",
        "Password": "Login",
        "Solar Panel": "Sunlight",
        "Self-Driving Car": "Autonomous",
        "Emoji": "Expression",
    },
    "Jobs": {
        "Doctor": "Stethoscope",
        "Teacher": "Classroom",
        "Firefighter": "Rescue",
        "Chef": "Kitchen",
        "Police Officer": "Patrol",
        "Farmer": "Harvest",
        "Singer": "Melody",
        "Baker": "Oven",
        "Driver": "Route",
        "Artist": "Canvas",
        "Pilot": "Cockpit",
        "Dentist": "Cavity",
        "Lifeguard": "Whistle",
        "Mechanic": "Engine",
        "Photographer": "Lens",
        "Nurse": "Ward",
        "Waiter": "Order",
        "Scientist": "Laboratory",
        "Soldier": "Battalion",
        "Barber": "Clippers",
        "Veterinarian": "Clinic",
        "Tour Guide": "Itinerary",
        "Astronaut": "Spacesuit",
        "Architect": "Blueprint",
        "Magician": "Illusion",
        "Librarian": "Catalog",
        "Detective": "Clues",
        "Plumber": "Pipes",
        "Judge": "Verdict",
        "Zookeeper": "Enclosure",
        "Stuntman": "Daredevil",
        "Lawyer": "Courtroom",
        "Electrician": "Wiring",
        "DJ": "Turntable",
    },
    "Sports": {
        "Basketball": "Hoop",
        "Football": "Goalpost",
        "Swimming": "Lap",
        "Tennis": "Racket",
        "Boxing": "Punch",
        "Running": "Marathon",
        "Volleyball": "Spike",
        "Baseball": "Diamond",
        "Badminton": "Shuttlecock",
        "Golf": "Fairway",
        "Skateboarding": "Ramp",
        "Bowling": "Strike",
        "Surfing": "Wave",
        "Cycling": "Pedal",
        "Table Tennis": "Paddle",
        "Wrestling": "Grapple",
        "Fencing": "Duel",
        "Archery": "Bullseye",
        "Curling": "Ice",
        "Gymnastics": "Flexibility",
        "Sumo": "Ring",
        "Polo": "Mallet",
        "Rock Climbing": "Cliffside",
        "Billiards": "Cue",
    },
    "Music": {
        "Piano": "Keys",
        "Drums": "Rhythm",
        "Violin": "Strings",
        "Karaoke": "Lyrics",
        "Concert": "Stage",
        "Microphone": "Amplify",
        "Trumpet": "Brass",
        "Lullaby": "Sleepy",
        "Saxophone": "Jazzy",
        "Ukulele": "Island",
        "Harmonica": "Tiny",
        "Rap": "Verses",
        "Choir": "Harmony",
        "Orchestra": "Conductor",
        "Flute": "Woodwind",
        "Jazz": "Improvise",
        "Accordion": "Bellows",
        "Harp": "Angelic",
        "Xylophone": "Mallets",
        "Opera": "Aria",
        "Bagpipes": "Scotland",
        "Metronome": "Tempo",
        "Tambourine": "Jingle",
        "Cello": "Deep",
    },
    "Countries": {
        "Philippines": "Archipelago",
        "Japan": "Sakura",
        "USA": "Eagle",
        "China": "Dynasty",
        "France": "Romance",
        "Italy": "Colosseum",
        "Brazil": "Carnival",
        "Australia": "Outback",
        "Mexico": "Fiesta",
        "Egypt": "Pharaoh",
        "India": "Monsoon",
        "Canada": "Maple",
        "Korea": "Peninsula",
        "Spain": "Flamenco",
        "Thailand": "Temples",
        "Germany": "Oktoberfest",
        "Iceland": "Geysers",
        "Peru": "Andes",
        "Greece": "Mythology",
        "Kenya": "Savanna",
        "Switzerland": "Alps",
        "Norway": "Fjords",
        "Vietnam": "Paddies",
        "Turkey": "Bazaar",
    },
    "Clothing": {
        "Shirt": "Button",
        "Hat": "Brim",
        "Socks": "Toes",
        "Jeans": "Denim",
        "Dress": "Gown",
        "Jacket": "Zipper",
        "Shoes": "Laces",
        "Pajamas": "Bedtime",
        "Scarf": "Cozy",
        "Gloves": "Fingers",
        "Hoodie": "Casual",
        "Sunglasses": "Shade",
        "Raincoat": "Drizzle",
        "Sandals": "Barefoot",
        "Necktie": "Formal",
        "Uniform": "Matching",
        "Tuxedo": "Gala",
        "Kimono": "Sash",
        "Barong": "Embroidered",
        "Overalls": "Farmhand",
        "Apron": "Stains",
        "Bow Tie": "Dapper",
        "Swimsuit": "Poolside",
        "Crown": "Royalty",
    },
    "Vehicles": {
        "Car": "Highway",
        "Bus": "Commute",
        "Bicycle": "Pedal",
        "Airplane": "Runway",
        "Train": "Tracks",
        "Boat": "Harbor",
        "Motorcycle": "Roar",
        "Taxi": "Fare",
        "Jeepney": "Colorful",
        "Helicopter": "Rotor",
        "Ambulance": "Siren",
        "Fire Truck": "Hose",
        "Tricycle": "Sidecar",
        "Skateboard": "Wheels",
        "Truck": "Cargo",
        "Yacht": "Luxury",
        "Hot Air Balloon": "Basket",
        "Rocket": "Launchpad",
        "Tank": "Armored",
        "Cable Car": "Summit",
        "Gondola": "Venice",
        "Bulldozer": "Rubble",
        "Canoe": "Paddle",
        "Zeppelin": "Blimp",
    },
    "Hobbies": {
        "Reading": "Novel",
        "Dancing": "Rhythm",
        "Cooking": "Recipe",
        "Drawing": "Sketch",
        "Singing": "Tune",
        "Fishing": "Bait",
        "Gaming": "Console",
        "Shopping": "Mall",
        "Camping": "Tent",
        "Gardening": "Soil",
        "Knitting": "Yarn",
        "Photography": "Lens",
        "Hiking": "Trail",
        "Baking": "Dough",
        "Yoga": "Stretch",
        "Puzzles": "Pieces",
        "Origami": "Folding",
        "Scuba Diving": "Underwater",
        "Pottery": "Clay",
        "Magic Tricks": "Illusion",
        "Birdwatching": "Binoculars",
        "Juggling": "Toss",
        "Calligraphy": "Script",
        "Chess": "Checkmate",
    },
    "Nature": {
        "Sun": "Daylight",
        "Moon": "Crescent",
        "Rain": "Puddles",
        "Tree": "Roots",
        "Flower": "Petals",
        "Rainbow": "Arc",
        "Mountain": "Peak",
        "Ocean": "Tides",
        "Waterfall": "Plunge",
        "Thunder": "Boom",
        "Forest": "Canopy",
        "Cave": "Darkness",
        "River": "Stream",
        "Snow": "Flurry",
        "Cloud": "Drift",
        "Island": "Shoreline",
        "Earthquake": "Tremor",
        "Tornado": "Funnel",
        "Glacier": "Frozen",
        "Coral Reef": "Vibrant",
        "Eclipse": "Shadow",
        "Quicksand": "Sinking",
        "Typhoon": "Gust",
        "Aurora": "Polar",
    },
    "Celebrations": {
        "Birthday": "Candles",
        "Christmas": "Ornaments",
        "Wedding": "Vows",
        "Halloween": "Costumes",
        "New Year": "Countdown",
        "Party": "Confetti",
        "Valentine's Day": "Roses",
        "Graduation": "Diploma",
        "Easter": "Basket",
        "Fiesta": "Bazaar",
        "Baby Shower": "Nursery",
        "Picnic": "Blanket",
        "Anniversary": "Milestone",
        "Fireworks": "Sparkle",
        "Parade": "March",
        "Reunion": "Nostalgia",
        "Debut": "Eighteen",
        "Thanksgiving": "Gratitude",
        "Chinese New Year": "Lanterns",
        "Carnival": "Costumed",
        "Funeral": "Mourning",
        "Prom": "Corsage",
        "Baptism": "Font",
        "Sleepover": "Overnight",
    },
    "Fantasy": {
        "Dragon": "Scales",
        "Unicorn": "Mythical",
        "Ghost": "Haunting",
        "Mermaid": "Lagoon",
        "Wizard": "Spellbook",
        "Fairy": "Pixie",
        "Vampire": "Fangs",
        "Zombie": "Undead",
        "Werewolf": "Howl",
        "Witch": "Cauldron",
        "Giant": "Towering",
        "Pirate": "Buccaneer",
        "Alien": "Extraterrestrial",
        "Genie": "Lamp",
        "Elf": "Archer",
        "Superhero": "Cape",
        "Phoenix": "Ashes",
        "Minotaur": "Labyrinth",
        "Kraken": "Abyss",
        "Aswang": "Folklore",
        "Tikbalang": "Legend",
        "Centaur": "Hooves",
        "Griffin": "Talons",
        "Yeti": "Himalayas",
    },
    "Household": {
        "Bed": "Mattress",
        "Sofa": "Cushions",
        "Fridge": "Chilled",
        "Door": "Hinge",
        "Window": "Glass",
        "Table": "Surface",
        "Lamp": "Glow",
        "Toilet": "Flush",
        "Bathtub": "Soak",
        "Washing Machine": "Spin",
        "Electric Fan": "Breeze",
        "Rice Cooker": "Steam",
        "Curtains": "Drapes",
        "Doormat": "Welcome",
        "Bookshelf": "Shelved",
        "Blender": "Puree",
        "Chandelier": "Crystals",
        "Fireplace": "Hearth",
        "Attic": "Dusty",
        "Dishwasher": "Rinse",
        "Hammock": "Sway",
        "Garage": "Toolbox",
        "Vacuum Cleaner": "Suction",
        "Ceiling Fan": "Spinning",
    },
    "Games & Toys": {
        "Ball": "Bounce",
        "Doll": "Playhouse",
        "Kite": "Breeze",
        "Yo-Yo": "String",
        "Teddy Bear": "Cuddly",
        "Lego": "Blocks",
        "Balloon": "Pop",
        "Playing Cards": "Deck",
        "Monopoly": "Bankrupt",
        "Hide and Seek": "Counting",
        "Jenga": "Wobble",
        "Rubik's Cube": "Twist",
        "Slide": "Playground",
        "Tag": "Chase",
        "Marbles": "Rolling",
        "Water Gun": "Squirt",
        "Piñata": "Candy",
        "Dominoes": "Toppling",
        "Hopscotch": "Chalk",
        "Jigsaw Puzzle": "Interlocking",
        "Spinning Top": "Twirl",
        "Trampoline": "Bouncy",
        "Bingo": "Numbers",
        "Sudoku": "Grid",
    },
    "Body": {
        "Nose": "Sniff",
        "Hand": "Grip",
        "Eye": "Blink",
        "Ear": "Lobe",
        "Hair": "Strands",
        "Mouth": "Lips",
        "Foot": "Toes",
        "Teeth": "Enamel",
        "Elbow": "Bend",
        "Knee": "Joint",
        "Tongue": "Taste",
        "Shoulder": "Carry",
        "Eyebrow": "Arch",
        "Belly Button": "Navel",
        "Thumb": "Grip",
        "Heart": "Pulse",
        "Skeleton": "Bones",
        "Brain": "Thoughts",
        "Ankle": "Sprain",
        "Lungs": "Breath",
        "Wrist": "Pulse",
        "Dimple": "Smile",
        "Fingerprint": "Unique",
        "Freckles": "Speckled",
    },
    "Brands": {
        "Nike": "Swoosh",
        "Apple": "Silicon",
        "McDonald's": "Arches",
        "Coca-Cola": "Fizzy",
        "Samsung": "Galaxy",
        "Google": "Search",
        "Disney": "Fairytale",
        "Jollibee": "Mascot",
        "KFC": "Colonel",
        "Adidas": "Stripes",
        "Starbucks": "Mermaid",
        "Netflix": "Streaming",
        "IKEA": "Flatpack",
        "Toyota": "Reliable",
        "Amazon": "Shipping",
        "YouTube": "Upload",
        "7-Eleven": "Convenience",
        "Shopee": "Checkout",
        "Rolex": "Timepiece",
        "Tesla": "Electric",
        "Gucci": "Designer",
        "Ferrari": "Prancing",
        "Nintendo": "Console",
        "Spotify": "Playlist",
        "Louis Vuitton": "Monogram",
        "Red Bull": "Caffeine",
        "Lamborghini": "Supercar",
    },
    "Celebrities": {
        "Taylor Swift": "Eras",
        "Beyoncé": "Queen",
        "Cristiano Ronaldo": "Forward",
        "Lionel Messi": "Dribble",
        "Michael Jackson": "Moonwalk",
        "Elvis Presley": "Rockabilly",
        "Lady Gaga": "Theatrical",
        "Rihanna": "Fenty",
        "Leonardo DiCaprio": "Oscar",
        "Justin Bieber": "Discovered",
        "Ariana Grande": "Ponytail",
        "Ed Sheeran": "Acoustic",
        "Billie Eilish": "Whisper",
        "Dwayne Johnson": "Wrestler",
        "Tom Cruise": "Daredevil",
        "Oprah Winfrey": "Talkshow",
        "Keanu Reeves": "Humble",
        "Bruno Mars": "Groovy",
        "Elon Musk": "Billionaire",
        "MrBeast": "Giveaway",
        "BTS": "Kpop",
        "Zendaya": "Versatile",
        "Bad Bunny": "Reggaeton",
        "Kim Kardashian": "Socialite",
        "Gordon Ramsay": "Fiery",
        "Jackie Chan": "Stunts",
        "Shakira": "Hips",
        "Selena Gomez": "Disney",
        "LeBron James": "Dunking",
    },
    "Pinoy Celebrities": {
        "Manny Pacquiao": "Champion",
        "Vice Ganda": "Comedian",
        "Sarah Geronimo": "Popstar",
        "Kathryn Bernardo": "Teleserye",
        "Daniel Padilla": "Heartthrob",
        "Coco Martin": "Primetime",
        "Anne Curtis": "Host",
        "Marian Rivera": "Glamorous",
        "Dingdong Dantes": "Superhero",
        "Vic Sotto": "Noontime",
        "Pia Wurtzbach": "Pageant",
        "Catriona Gray": "Crowned",
        "Regine Velasquez": "Songbird",
        "Lea Salonga": "Broadway",
        "Alden Richards": "Viral",
        "Maine Mendoza": "Dance",
        "Nadine Lustre": "Indie",
        "James Reid": "Crooner",
        "Liza Soberano": "Beauty",
        "Enrique Gil": "Dashing",
        "SB19": "Boyband",
        "BINI": "Girlgroup",
        "Dolphy": "Comedy",
        "Nora Aunor": "Superstar",
        "Sharon Cuneta": "Megastar",
        "Ivana Alawi": "Influencer",
        "Mimiyuuuh": "Vlogger",
        "Toni Gonzaga": "Showbiz",
        "Jessica Soho": "Journalist",
        "Hidilyn Diaz": "Weightlifting",
        "Carlos Yulo": "Gymnast",
        "Arnel Pineda": "Frontman",
    },
    "Fictional Characters": {
        "Mickey Mouse": "Clubhouse",
        "SpongeBob": "Pineapple",
        "Pikachu": "Thunderbolt",
        "Mario": "Mushroom",
        "Superman": "Krypton",
        "Elsa": "Snowflake",
        "Darth Vader": "Sith",
        "Barbie": "Dreamhouse",
        "Cinderella": "Slipper",
        "Sherlock Holmes": "Deduction",
        "Hermione Granger": "Bookworm",
        "Iron Man": "Billionaire",
        "Buzz Lightyear": "Infinity",
        "Winnie the Pooh": "Honeycomb",
        "Homer Simpson": "Doughnut",
        "Sonic": "Speedy",
        "Hello Kitty": "Bow",
        "Doraemon": "Gadget",
        "Naruto": "Ninja",
        "Goku": "Saiyan",
        "Dora the Explorer": "Backpack",
        "Darna": "Transform",
        "Captain Barbell": "Dumbbells",
        "Gollum": "Precious",
        "Sailor Moon": "Crescent",
        "Scooby-Doo": "Mystery",
        "Garfield": "Lasagna",
        "Wednesday Addams": "Deadpan",
        "Jack Sparrow": "Caribbean",
        "Dracula": "Transylvania",
        "Pinocchio": "Puppet",
        "Luffy": "Strawhat",
    },
}
