# category -> (description, {difficulty: [words]})
SEED_DATA: dict[str, tuple[str, dict[str, list[str]]]] = {
    "Animals": (
        "Creatures great and small",
        {
            "easy": [
                "Dog",
                "Cat",
                "Elephant",
                "Giraffe",
                "Penguin",
                "Lion",
                "Monkey",
                "Horse",
                "Rabbit",
                "Shark",
                "Tiger",
            ],
            "medium": [
                "Dolphin",
                "Octopus",
                "Kangaroo",
                "Owl",
                "Crocodile",
                "Bat",
                "Camel",
                "Flamingo",
                "Koala",
                "Peacock",
                "Squirrel",
                "Turtle",
            ],
            "hard": [
                "Platypus",
                "Chameleon",
                "Sloth",
                "Jellyfish",
                "Armadillo",
                "Narwhal",
                "Hedgehog",
                "Seahorse",
                "Porcupine",
                "Carabao",
                "Tarsier",
            ],
        },
    ),
    "Food": (
        "Things to eat",
        {
            "easy": [
                "Pizza",
                "Burger",
                "Ice Cream",
                "Pancakes",
                "Spaghetti",
                "Fried Chicken",
                "Hotdog",
                "French Fries",
                "Sandwich",
                "Chocolate",
                "Donut",
            ],
            "medium": [
                "Sushi",
                "Tacos",
                "Adobo",
                "Ramen",
                "Popcorn",
                "Lasagna",
                "Dumplings",
                "Sinigang",
                "Lumpia",
                "Burrito",
                "Curry",
                "Waffles",
                "Cheesecake",
            ],
            "hard": [
                "Halo-Halo",
                "Lechon",
                "Fondue",
                "Paella",
                "Croissant",
                "Kimchi",
                "Balut",
                "Kare-Kare",
                "Tiramisu",
                "Pho",
                "Bibimbap",
                "Sisig",
            ],
        },
    ),
    "Places": (
        "Locations and destinations",
        {
            "easy": [
                "Beach",
                "School",
                "Hospital",
                "Airport",
                "Zoo",
                "Supermarket",
                "Park",
                "Mall",
                "Restaurant",
                "Playground",
            ],
            "medium": [
                "Library",
                "Museum",
                "Cinema",
                "Gym",
                "Church",
                "Bakery",
                "Farm",
                "Hotel",
                "Stadium",
                "Train Station",
                "Water Park",
                "Barber Shop",
                "Karaoke Bar",
            ],
            "hard": [
                "Lighthouse",
                "Casino",
                "Submarine",
                "Space Station",
                "Volcano",
                "Prison",
                "Castle",
                "Igloo",
                "Haunted House",
                "Cruise Ship",
                "Desert Island",
                "Observatory",
            ],
        },
    ),
    "Objects": (
        "Everyday things",
        {
            "easy": [
                "Chair",
                "Umbrella",
                "Toothbrush",
                "Pillow",
                "Clock",
                "Mirror",
                "Spoon",
                "Key",
                "Book",
                "Cup",
            ],
            "medium": [
                "Backpack",
                "Candle",
                "Scissors",
                "Wallet",
                "Ladder",
                "Guitar",
                "Flashlight",
                "Paintbrush",
                "Basket",
                "Hammer",
                "Remote Control",
            ],
            "hard": [
                "Compass",
                "Hourglass",
                "Stapler",
                "Magnifying Glass",
                "Thermometer",
                "Telescope",
                "Anchor",
                "Doorbell",
                "Calculator",
                "Paper Clip",
            ],
        },
    ),
    "Movies": (
        "Famous films",
        {
            "easy": [
                "Titanic",
                "Frozen",
                "Toy Story",
                "Shrek",
                "Jurassic Park",
                "Finding Nemo",
                "Cars",
                "Moana",
                "Minions",
                "Coco",
            ],
            "medium": [
                "The Lion King",
                "Avatar",
                "Harry Potter",
                "Star Wars",
                "Spider-Man",
                "Avengers",
                "Batman",
                "Encanto",
                "Kung Fu Panda",
                "Ghostbusters",
                "Home Alone",
            ],
            "hard": [
                "Inception",
                "Parasite",
                "The Matrix",
                "Jaws",
                "Up",
                "Interstellar",
                "Gravity",
                "Ratatouille",
                "Top Gun",
                "Godzilla",
                "The Godfather",
                "Back to the Future",
            ],
        },
    ),
    "Technology": (
        "Gadgets and tech",
        {
            "easy": [
                "Smartphone",
                "Laptop",
                "Television",
                "Headphones",
                "Camera",
                "Keyboard",
                "Tablet",
                "Video Game",
                "Charger",
            ],
            "medium": [
                "Drone",
                "Smartwatch",
                "Robot",
                "Printer",
                "Microwave",
                "Wi-Fi",
                "Selfie Stick",
                "Speaker",
                "Game Console",
                "Power Bank",
                "Electric Scooter",
            ],
            "hard": [
                "Bluetooth",
                "Satellite",
                "Virtual Reality",
                "Cloud Storage",
                "QR Code",
                "Artificial Intelligence",
                "3D Printer",
                "Password",
                "Solar Panel",
                "Self-Driving Car",
                "Emoji",
            ],
        },
    ),
    "Jobs": (
        "Occupations",
        {
            "easy": [
                "Doctor",
                "Teacher",
                "Firefighter",
                "Chef",
                "Police Officer",
                "Farmer",
                "Singer",
                "Baker",
                "Driver",
                "Artist",
            ],
            "medium": [
                "Pilot",
                "Dentist",
                "Lifeguard",
                "Mechanic",
                "Photographer",
                "Nurse",
                "Waiter",
                "Scientist",
                "Soldier",
                "Barber",
                "Veterinarian",
                "Tour Guide",
            ],
            "hard": [
                "Astronaut",
                "Architect",
                "Magician",
                "Librarian",
                "Detective",
                "Plumber",
                "Judge",
                "Zookeeper",
                "Stuntman",
                "Lawyer",
                "Electrician",
                "DJ",
            ],
        },
    ),
    "Sports": (
        "Games, athletes and arenas",
        {
            "easy": [
                "Basketball",
                "Football",
                "Swimming",
                "Tennis",
                "Boxing",
                "Running",
                "Volleyball",
                "Baseball",
            ],
            "medium": [
                "Badminton",
                "Golf",
                "Skateboarding",
                "Bowling",
                "Surfing",
                "Cycling",
                "Table Tennis",
                "Wrestling",
            ],
            "hard": [
                "Fencing",
                "Archery",
                "Curling",
                "Gymnastics",
                "Sumo",
                "Polo",
                "Rock Climbing",
                "Billiards",
            ],
        },
    ),
    "Music": (
        "Instruments, genres and sounds",
        {
            "easy": [
                "Piano",
                "Drums",
                "Violin",
                "Karaoke",
                "Concert",
                "Microphone",
                "Trumpet",
                "Lullaby",
            ],
            "medium": [
                "Saxophone",
                "Ukulele",
                "Harmonica",
                "Rap",
                "Choir",
                "Orchestra",
                "Flute",
                "Jazz",
            ],
            "hard": [
                "Accordion",
                "Harp",
                "Xylophone",
                "Opera",
                "Bagpipes",
                "Metronome",
                "Tambourine",
                "Cello",
            ],
        },
    ),
    "Countries": (
        "Nations around the world",
        {
            "easy": [
                "Philippines",
                "Japan",
                "USA",
                "China",
                "France",
                "Italy",
                "Brazil",
                "Australia",
            ],
            "medium": [
                "Mexico",
                "Egypt",
                "India",
                "Canada",
                "Korea",
                "Spain",
                "Thailand",
                "Germany",
            ],
            "hard": [
                "Iceland",
                "Peru",
                "Greece",
                "Kenya",
                "Switzerland",
                "Norway",
                "Vietnam",
                "Turkey",
            ],
        },
    ),
    "Clothing": (
        "Things to wear",
        {
            "easy": ["Shirt", "Hat", "Socks", "Jeans", "Dress", "Jacket", "Shoes", "Pajamas"],
            "medium": [
                "Scarf",
                "Gloves",
                "Hoodie",
                "Sunglasses",
                "Raincoat",
                "Sandals",
                "Necktie",
                "Uniform",
            ],
            "hard": [
                "Tuxedo",
                "Kimono",
                "Barong",
                "Overalls",
                "Apron",
                "Bow Tie",
                "Swimsuit",
                "Crown",
            ],
        },
    ),
    "Vehicles": (
        "Ways to get around",
        {
            "easy": [
                "Car",
                "Bus",
                "Bicycle",
                "Airplane",
                "Train",
                "Boat",
                "Motorcycle",
                "Taxi",
            ],
            "medium": [
                "Jeepney",
                "Helicopter",
                "Ambulance",
                "Fire Truck",
                "Tricycle",
                "Skateboard",
                "Truck",
                "Yacht",
            ],
            "hard": [
                "Hot Air Balloon",
                "Rocket",
                "Tank",
                "Cable Car",
                "Gondola",
                "Bulldozer",
                "Canoe",
                "Zeppelin",
            ],
        },
    ),
    "Hobbies": (
        "Things people do for fun",
        {
            "easy": [
                "Reading",
                "Dancing",
                "Cooking",
                "Drawing",
                "Singing",
                "Fishing",
                "Gaming",
                "Shopping",
            ],
            "medium": [
                "Camping",
                "Gardening",
                "Knitting",
                "Photography",
                "Hiking",
                "Baking",
                "Yoga",
                "Puzzles",
            ],
            "hard": [
                "Origami",
                "Scuba Diving",
                "Pottery",
                "Magic Tricks",
                "Birdwatching",
                "Juggling",
                "Calligraphy",
                "Chess",
            ],
        },
    ),
    "Nature": (
        "The great outdoors",
        {
            "easy": [
                "Sun",
                "Moon",
                "Rain",
                "Tree",
                "Flower",
                "Rainbow",
                "Mountain",
                "Ocean",
            ],
            "medium": [
                "Waterfall",
                "Thunder",
                "Forest",
                "Cave",
                "River",
                "Snow",
                "Cloud",
                "Island",
            ],
            "hard": [
                "Earthquake",
                "Tornado",
                "Glacier",
                "Coral Reef",
                "Eclipse",
                "Quicksand",
                "Typhoon",
                "Aurora",
            ],
        },
    ),
    "Celebrations": (
        "Holidays and special occasions",
        {
            "easy": [
                "Birthday",
                "Christmas",
                "Wedding",
                "Halloween",
                "New Year",
                "Party",
                "Valentine's Day",
                "Graduation",
            ],
            "medium": [
                "Easter",
                "Fiesta",
                "Baby Shower",
                "Picnic",
                "Anniversary",
                "Fireworks",
                "Parade",
                "Reunion",
            ],
            "hard": [
                "Debut",
                "Thanksgiving",
                "Chinese New Year",
                "Carnival",
                "Funeral",
                "Prom",
                "Baptism",
                "Sleepover",
            ],
        },
    ),
    "Fantasy": (
        "Myths, magic and monsters",
        {
            "easy": [
                "Dragon",
                "Unicorn",
                "Ghost",
                "Mermaid",
                "Wizard",
                "Fairy",
                "Vampire",
                "Zombie",
            ],
            "medium": [
                "Werewolf",
                "Witch",
                "Giant",
                "Pirate",
                "Alien",
                "Genie",
                "Elf",
                "Superhero",
            ],
            "hard": [
                "Phoenix",
                "Minotaur",
                "Kraken",
                "Aswang",
                "Tikbalang",
                "Centaur",
                "Griffin",
                "Yeti",
            ],
        },
    ),
    "Household": (
        "Around the house",
        {
            "easy": ["Bed", "Sofa", "Fridge", "Door", "Window", "Table", "Lamp", "Toilet"],
            "medium": [
                "Bathtub",
                "Washing Machine",
                "Electric Fan",
                "Rice Cooker",
                "Curtains",
                "Doormat",
                "Bookshelf",
                "Blender",
            ],
            "hard": [
                "Chandelier",
                "Fireplace",
                "Attic",
                "Dishwasher",
                "Hammock",
                "Garage",
                "Vacuum Cleaner",
                "Ceiling Fan",
            ],
        },
    ),
    "Games & Toys": (
        "Things to play with",
        {
            "easy": [
                "Ball",
                "Doll",
                "Kite",
                "Yo-Yo",
                "Teddy Bear",
                "Lego",
                "Balloon",
                "Playing Cards",
            ],
            "medium": [
                "Monopoly",
                "Hide and Seek",
                "Jenga",
                "Rubik's Cube",
                "Slide",
                "Tag",
                "Marbles",
                "Water Gun",
            ],
            "hard": [
                "Piñata",
                "Dominoes",
                "Hopscotch",
                "Jigsaw Puzzle",
                "Spinning Top",
                "Trampoline",
                "Bingo",
                "Sudoku",
            ],
        },
    ),
    "Body": (
        "Parts of the body",
        {
            "easy": ["Nose", "Hand", "Eye", "Ear", "Hair", "Mouth", "Foot", "Teeth"],
            "medium": [
                "Elbow",
                "Knee",
                "Tongue",
                "Shoulder",
                "Eyebrow",
                "Belly Button",
                "Thumb",
                "Heart",
            ],
            "hard": [
                "Skeleton",
                "Brain",
                "Ankle",
                "Lungs",
                "Wrist",
                "Dimple",
                "Fingerprint",
                "Freckles",
            ],
        },
    ),
    "Brands": (
        "Famous companies and products",
        {
            "easy": [
                "Nike",
                "Apple",
                "McDonald's",
                "Coca-Cola",
                "Samsung",
                "Google",
                "Disney",
                "Jollibee",
                "KFC",
            ],
            "medium": [
                "Adidas",
                "Starbucks",
                "Netflix",
                "IKEA",
                "Toyota",
                "Amazon",
                "YouTube",
                "7-Eleven",
                "Shopee",
            ],
            "hard": [
                "Rolex",
                "Tesla",
                "Gucci",
                "Ferrari",
                "Nintendo",
                "Spotify",
                "Louis Vuitton",
                "Red Bull",
                "Lamborghini",
            ],
        },
    ),
}
