"""game categories many to many

Revision ID: 25d2fab68a20
Revises: a68a66647cc5
Create Date: 2026-10-06 08:53:24.275472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d2fab68a20'
down_revision: Union[str, Sequence[str], None] = 'a68a66647cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_categories',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_game_categories_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_categories_game_id_games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'category_id', name=op.f('pk_game_categories'))
    )
    op.create_index(op.f('ix_game_categories_category_id'), 'game_categories', ['category_id'], unique=False)

    # Carry over each game's single category; games whose category was deleted become random.
    op.execute(
        "INSERT INTO game_categories (game_id, category_id) "
        "SELECT id, category_id FROM games WHERE category_id IS NOT NULL"
    )
    op.execute(
        "UPDATE games SET category_mode = 'random' "
        "WHERE category_mode = 'specific' AND category_id IS NULL"
    )

    # Dropping the column also drops ck_games_specific_category_set.
    op.drop_index(op.f('ix_games_category_id'), table_name='games')
    op.drop_constraint(op.f('fk_games_category_id_categories'), 'games', type_='foreignkey')
    op.drop_column('games', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_games_category_id_categories'), 'games', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_games_category_id'), 'games', ['category_id'], unique=False)

    # Keep one category per game (the lowest id); games left without one become random.
    op.execute(
        "UPDATE games SET category_id = "
        "(SELECT min(category_id) FROM game_categories gc WHERE gc.game_id = games.id)"
    )
    op.execute(
        "UPDATE games SET category_mode = 'random' "
        "WHERE category_mode = 'specific' AND category_id IS NULL"
    )
    op.create_check_constraint(
        op.f('ck_games_specific_category_set'),
        'games',
        "category_mode = 'random' OR category_id IS NOT NULL",
    )

    op.drop_index(op.f('ix_game_categories_category_id'), table_name='game_categories')
    op.drop_table('game_categories')
    # ### end Alembic commands ###
