"""initial schema

Revision ID: 59d0eba41bf0
Revises: 
Create Date: 2026-10-06 08:17:55.968460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d0eba41bf0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index('uq_categories_name_lower', 'categories', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('total_rounds', sa.Integer(), nullable=False),
    sa.Column('category_mode', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('impostor_hint', sa.String(length=20), nullable=False),
    sa.Column('starting_player_mode', sa.String(length=20), nullable=False),
    sa.Column('current_round_number', sa.Integer(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category_mode = 'random' OR category_id IS NOT NULL", name=op.f('ck_games_specific_category_set')),
    sa.CheckConstraint("category_mode IN ('random', 'specific')", name=op.f('ck_games_category_mode_valid')),
    sa.CheckConstraint("impostor_hint IN ('none', 'category')", name=op.f('ck_games_impostor_hint_valid')),
    sa.CheckConstraint("starting_player_mode IN ('random', 'after_impostor')", name=op.f('ck_games_starting_player_mode_valid')),
    sa.CheckConstraint("state IN ('SETUP', 'ROLE_REVEAL', 'READY', 'CLUE_ROUND', 'VOTING', 'IMPOSTOR_REVEAL', 'FINAL_GUESS', 'ROUND_RESULTS', 'GAME_RESULTS')", name=op.f('ck_games_state_valid')),
    sa.CheckConstraint('total_rounds > 0', name=op.f('ck_games_total_rounds_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_games_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    op.create_index(op.f('ix_games_category_id'), 'games', ['category_id'], unique=False)
    op.create_index(op.f('ix_games_state'), 'games', ['state'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=80), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("difficulty IN ('easy', 'medium', 'hard')", name=op.f('ck_words_difficulty_valid')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_words_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_words'))
    )
    op.create_index(op.f('ix_words_category_id'), 'words', ['category_id'], unique=False)
    op.create_index(op.f('ix_words_difficulty'), 'words', ['difficulty'], unique=False)
    op.create_index('uq_words_category_word_lower', 'words', ['category_id', sa.literal_column('lower(word)')], unique=True)
    op.create_table('game_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_players_game_id_games'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_players')),
    sa.UniqueConstraint('game_id', 'order_index', name=op.f('uq_game_players_game_id'))
    )
    op.create_index('uq_game_players_game_name_lower', 'game_players', ['game_id', sa.literal_column('lower(name)')], unique=True)
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(length=50), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.Column('secret_word', sa.String(length=80), nullable=False),
    sa.Column('impostor_id', sa.Integer(), nullable=False),
    sa.Column('starting_player_id', sa.Integer(), nullable=False),
    sa.Column('suspect_id', sa.Integer(), nullable=True),
    sa.Column('reveal_index', sa.Integer(), nullable=False),
    sa.Column('word_revealed', sa.Boolean(), nullable=False),
    sa.Column('impostor_caught', sa.Boolean(), nullable=True),
    sa.Column('final_guess_correct', sa.Boolean(), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IS NULL OR outcome IN ('group_wins', 'impostor_escaped', 'impostor_guessed_word')", name=op.f('ck_rounds_outcome_valid')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_rounds_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_rounds_game_id_games'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['impostor_id'], ['game_players.id'], name=op.f('fk_rounds_impostor_id_game_players')),
    sa.ForeignKeyConstraint(['starting_player_id'], ['game_players.id'], name=op.f('fk_rounds_starting_player_id_game_players')),
    sa.ForeignKeyConstraint(['suspect_id'], ['game_players.id'], name=op.f('fk_rounds_suspect_id_game_players')),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], name=op.f('fk_rounds_word_id_words'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rounds')),
    sa.UniqueConstraint('game_id', 'round_number', name=op.f('uq_rounds_game_id'))
    )
    op.create_index(op.f('ix_rounds_category_id'), 'rounds', ['category_id'], unique=False)
    op.create_index(op.f('ix_rounds_impostor_id'), 'rounds', ['impostor_id'], unique=False)
    op.create_index(op.f('ix_rounds_word_id'), 'rounds', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rounds_word_id'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_impostor_id'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_category_id'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_index('uq_game_players_game_name_lower', table_name='game_players')
    op.drop_table('game_players')
    op.drop_index('uq_words_category_word_lower', table_name='words')
    op.drop_index(op.f('ix_words_difficulty'), table_name='words')
    op.drop_index(op.f('ix_words_category_id'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_games_state'), table_name='games')
    op.drop_index(op.f('ix_games_category_id'), table_name='games')
    op.drop_table('games')
    op.drop_index('uq_categories_name_lower', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
