"""impostors know each other

Revision ID: 929eda6cd7ca
Revises: 38510158fb9a
Create Date: 2026-10-06 09:37:24.167645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '929eda6cd7ca'
down_revision: Union[str, Sequence[str], None] = '38510158fb9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('impostors_know_each_other', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'impostors_know_each_other')
    # ### end Alembic commands ###
